#!/usr/bin/env bash
# Render Build Script for FitnessFun Flutter Web App
# This script is called by Render during the build process

set -e  # Exit on error

echo "=== FitnessFun Render Build ==="

# --- Configuration ---
FLUTTER_VERSION="${FLUTTER_VERSION:-3.27.1}"
FLUTTER_CHANNEL="stable"

# --- Install Flutter ---
echo "Installing Flutter ${FLUTTER_VERSION}..."

# Clone Flutter if not present
if [ ! -d "$HOME/flutter" ]; then
  git clone https://github.com/flutter/flutter.git -b ${FLUTTER_VERSION} --depth 1 "$HOME/flutter"
fi

# Add Flutter to PATH
export PATH="$HOME/flutter/bin:$PATH"

# Verify Flutter installation
flutter --version
flutter doctor -v

# --- Create .env file from environment variables ---
echo "Creating .env file from environment variables..."

if [ -z "$SUPABASE_URL" ]; then
  echo "ERROR: SUPABASE_URL environment variable is not set"
  exit 1
fi

if [ -z "$SUPABASE_ANON_KEY" ]; then
  echo "ERROR: SUPABASE_ANON_KEY environment variable is not set"
  exit 1
fi

cat > .env << EOF
# Generated by render-build.sh
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
EOF

echo ".env file created successfully"

# --- Install dependencies ---
echo "Installing Flutter dependencies..."
flutter pub get

# --- Run code generation ---
echo "Running build_runner for code generation..."
dart run build_runner build --delete-conflicting-outputs

# --- Build Flutter Web ---
echo "Building Flutter web app..."
flutter build web --release --web-renderer html

echo "=== Build Complete ==="
echo "Output directory: build/web"
ls -la build/web/
